Repository NVIDIA/container-canary, pull requests merged in 2022-08, with the labels that each got.

#35 feat: Improve error handling
  cmd/validate.go
  go.mod
  go.sum
  internal/container/docker.go
Labels: bug

#36 Add linting
  .github/workflows/lint.yaml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  cmd/root_test.go
  cmd/version.go
  cmd/version_test.go
  internal/container/docker_test.go
Labels: documentation, enhancement, CI

#37 Add error checking to container cleanup
  internal/container/docker.go
Labels: hygeine
